# Generated by Django 2.2.2 on 2019-06-23 09:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.SmallIntegerField(choices=[(1, 'Kobieta'), (2, 'Mężczyzna')], default=1)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Aktywny'), (2, 'Nieaktywny')], default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(default='user_img/default.jpg', upload_to='user_img/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=0)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='control_panel.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.SmallIntegerField(choices=[(1, 'Kobieta'), (2, 'Mężczyzna')], default=1)),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Aktywny'), (2, 'Nieaktywny')], default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(default='trainer_img/default.jpg', upload_to='trainer_img/')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employment_type', models.SmallIntegerField(choices=[(1, 'UoP'), (2, 'UoZ'), (3, 'UoD'), (4, 'B2B')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'Karnet'), (2, 'Karta'), (3, 'Wejściówka')])),
                ('partner_name', models.SmallIntegerField(blank=True, choices=[(1, 'Multisport'), (2, 'Fit-Profit'), (3, 'OK System')], null=True)),
                ('validity', models.IntegerField(blank=True, null=True)),
                ('available_entries', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entry_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('absence_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='control_panel.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('current_pass', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='control_panel.Pass')),
            ],
        ),
        migrations.AddField(
            model_name='pass',
            name='product',
            field=models.ForeignKey(on_delete=None, related_name='products', to='control_panel.Product'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, 'Podstawowa'), (2, 'Średnio-zaawansowana'), (3, 'Zaawansowana')], default=1)),
                ('color', models.SmallIntegerField(choices=[(1, 'green'), (2, 'red'), (3, 'black'), (4, 'yellow'), (5, 'blue')])),
                ('max_capacity', models.IntegerField()),
                ('class_time', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='control_panel.Activity')),
                ('days', models.ManyToManyField(to='control_panel.Day')),
                ('members', models.ManyToManyField(to='control_panel.Member')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='control_panel.Trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('current_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='control_panel.Pass')),
            ],
        ),
    ]
