# Generated by Django 2.1.7 on 2019-03-19 21:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('level', models.SmallIntegerField(choices=[(1, 'Podstawowa'), (2, 'Średnio-zaawansowana'), (3, 'Zaawansowana')], default=1)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('max_capacity', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='control_panel.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.SmallIntegerField(choices=[(1, 'Kobieta'), (2, 'Mężczyzna')], default=1)),
                ('phone', models.IntegerField(null=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Aktywny'), (2, 'Nieaktywny')], default=1)),
                ('notes', models.TextField(null=True)),
                ('img', models.ImageField(default='user_img/default.jpg', upload_to='user_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('sent_date', models.DateTimeField(default=datetime.date.today)),
                ('recipient', models.ManyToManyField(to='control_panel.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=0)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='control_panel.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('validity', models.SmallIntegerField(default=30)),
                ('available_entries', models.SmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.SmallIntegerField(choices=[(1, 'Kobieta'), (2, 'Mężczyzna')], default=1)),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254, null=True, unique=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Aktywny'), (2, 'Nieaktywny')], default=1)),
                ('notes', models.TextField(null=True)),
                ('img', models.ImageField(default='trainer_img/default.jpg', upload_to='trainer_img/')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('employment_type', models.SmallIntegerField(choices=[(1, 'UoP'), (2, 'UoZ'), (3, 'UoD'), (4, 'B2B')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='pass',
            name='product',
            field=models.ForeignKey(on_delete=None, related_name='products', to='control_panel.Product'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='control_panel.Member'),
        ),
        migrations.AddField(
            model_name='group',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='control_panel.Trainer'),
        ),
        migrations.AddField(
            model_name='entry',
            name='current_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='control_panel.Pass'),
        ),
        migrations.AddField(
            model_name='classtime',
            name='days',
            field=models.ManyToManyField(to='control_panel.Day'),
        ),
        migrations.AddField(
            model_name='classtime',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.Group'),
        ),
        migrations.AddField(
            model_name='activity',
            name='products',
            field=models.ManyToManyField(to='control_panel.Product'),
        ),
        migrations.AddField(
            model_name='activity',
            name='trainers',
            field=models.ManyToManyField(to='control_panel.Trainer'),
        ),
    ]
