# Generated by Django 2.0.2 on 2018-03-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.TextField()),
                ('program', models.IntegerField(choices=[(1, 'Jumping'), (2, 'Pole Dance'), (3, 'Stretching')])),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone', models.IntegerField()),
                ('mail', models.TextField(unique=True)),
                ('terms', models.BooleanField()),
                ('status', models.SmallIntegerField(choices=[(1, 'active'), (2, 'not active')])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, '4'), (2, '8'), (3, '16'), (4, 'FitProfit'), (5, 'Multisport'), (6, 'Multisport + 80')])),
                ('price', models.IntegerField()),
                ('status', models.SmallIntegerField(choices=[(1, 'active'), (2, 'not active')])),
                ('entries', models.SmallIntegerField()),
                ('exp_date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='control_panel.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone', models.IntegerField()),
                ('mail', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='members',
            field=models.ManyToManyField(to='control_panel.Member'),
        ),
        migrations.AddField(
            model_name='class',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='control_panel.Trainer'),
        ),
    ]
