# Generated by Django 2.1.7 on 2019-03-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Data urodzenia'),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Kobieta'), (2, 'Mężczyzna')], default=1, verbose_name='Płeć'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Aktywny'), (2, 'Nie aktywny')], default=2, verbose_name='Status'),
        ),
    ]
