# Generated by Django 2.2.2 on 2019-06-23 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='control_panel.Activity'),
        ),
    ]
