# Generated by Django 2.1.7 on 2019-03-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
