# Generated by Django 2.0.2 on 2018-03-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='exp_date',
        ),
        migrations.AlterField(
            model_name='class',
            name='trainer',
            field=models.ForeignKey(on_delete=None, related_name='classes', to='control_panel.Trainer'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'paid'), (2, 'not paid')]),
        ),
        migrations.AlterField(
            model_name='pass',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '4'), (2, '8'), (3, '12'), (4, 'Open'), (5, 'FitProfit'), (6, 'Multisport'), (7, 'Multisport + 80')]),
        ),
    ]
