# Generated by Django 2.2.2 on 2019-09-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_auto_20190927_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='lng',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
