# Generated by Django 2.0.2 on 2018-03-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_auto_20180319_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
