# Generated by Django 2.1.7 on 2019-03-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_auto_20190314_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='description',
        ),
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Kobieta'), (2, 'Mężczyzna')], default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='member',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Aktywny'), (2, 'Nieaktywny')], default=2),
        ),
    ]
