# Generated by Django 2.2.2 on 2019-06-24 08:23

import control_panel.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_auto_20190623_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='color',
            field=control_panel.models.ColorField(max_length=10),
        ),
    ]
