# Generated by Django 2.0.2 on 2018-03-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_auto_20180320_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='terms',
        ),
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.TextField(null=True, verbose_name='Notatka'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(verbose_name='Numer tel.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'active'), (2, 'not active')], default=2, verbose_name='Status'),
        ),
    ]
