# Generated by Django 2.1.7 on 2019-03-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_auto_20190314_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='img',
            field=models.ImageField(null=True, upload_to='user_img/'),
        ),
    ]
