# Generated by Django 2.0.2 on 2018-03-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0004_auto_20180320_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'paid'), (2, 'not paid')], default=2),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='mail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
