# Generated by Django 2.1.7 on 2019-03-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0004_member_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(default='user_img/default.jpg', upload_to='user_img/'),
        ),
    ]
