# Generated by Django 2.2.2 on 2019-06-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0005_auto_20190627_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
    ]
