# Generated by Django 2.0.2 on 2018-03-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0005_auto_20180320_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='entries',
            field=models.SmallIntegerField(default=0),
        ),
    ]
