# Generated by Django 2.1.7 on 2019-03-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0005_auto_20190314_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='employment_type',
            field=models.SmallIntegerField(choices=[(1, 'UoP'), (2, 'UoZ'), (3, 'UoD'), (4, 'B2B')], default=1),
        ),
        migrations.AddField(
            model_name='trainer',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Kobieta'), (2, 'Mężczyzna')], default=1),
        ),
        migrations.AddField(
            model_name='trainer',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='img',
            field=models.ImageField(default='trainer_img/default.jpg', upload_to='trainer_img/'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Aktywny'), (2, 'Nieaktywny')], default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Aktywny'), (2, 'Nieaktywny')], default=1),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='mail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
