# Generated by Django 2.1.7 on 2019-03-19 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0005_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_time', to='control_panel.Group'),
        ),
    ]
