# Generated by Django 2.1.7 on 2019-03-16 22:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0006_auto_20190316_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pass',
            name='entries',
        ),
        migrations.RemoveField(
            model_name='product',
            name='activity',
        ),
        migrations.AddField(
            model_name='pass',
            name='available_entries',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='current_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='control_panel.Pass'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'Podstawowa'), (2, 'Średnio-zaawansowana'), (3, 'Zaawansowana')], default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='control_panel.Member'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='group',
            name='program',
            field=models.IntegerField(choices=[(1, 'Jumping'), (2, 'Pole Dance'), (3, 'Stretching')]),
        ),
        migrations.AlterField(
            model_name='group',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='control_panel.Trainer'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pass',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='control_panel.Member'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='product',
            field=models.ForeignKey(on_delete=None, related_name='products', to='control_panel.Product'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pass',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Opłacony'), (2, 'Do zapłaty')], default=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_entries',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='validity',
            field=models.SmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='activity',
            name='products',
            field=models.ManyToManyField(to='control_panel.Product'),
        ),
        migrations.AddField(
            model_name='activity',
            name='trainers',
            field=models.ManyToManyField(to='control_panel.Trainer'),
        ),
        migrations.AddField(
            model_name='group',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='control_panel.Activity'),
        ),
    ]
