# Generated by Django 2.0.2 on 2018-03-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0006_auto_20180320_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('validity', models.SmallIntegerField()),
                ('entries', models.SmallIntegerField()),
                ('activity', models.SmallIntegerField(choices=[(1, 'Jumping'), (2, 'Pole Dance'), (3, 'Stretching')])),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pass',
            name='entries',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='type',
        ),
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'Podstawowa'), (2, 'Średnio-zaawansowana'), (3, 'Zaawansowana')]),
        ),
        migrations.AddField(
            model_name='pass',
            name='product',
            field=models.ForeignKey(default=1, on_delete=None, to='control_panel.Product'),
            preserve_default=False,
        ),
    ]
