# Generated by Django 2.2.2 on 2019-06-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0006_auto_20190627_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='nip',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
