# Generated by Django 2.1.7 on 2019-03-24 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0007_auto_20190324_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtime',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='class_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='days',
            field=models.ManyToManyField(to='control_panel.Day'),
        ),
    ]
