# Generated by Django 2.1.7 on 2019-03-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0007_auto_20190316_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='program',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='available_entries',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='status',
        ),
        migrations.AddField(
            model_name='pass',
            name='paid',
            field=models.BooleanField(default=0),
        ),
    ]
