# Generated by Django 2.1.7 on 2019-03-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0008_auto_20190316_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='capacity',
        ),
    ]
