# Generated by Django 2.1.7 on 2019-03-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0008_auto_20190324_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='color',
            field=models.SmallIntegerField(choices=[(1, 'green'), (2, 'red'), (3, 'black'), (4, 'yellow'), (5, 'blue')]),
        ),
    ]
