# Generated by Django 2.2.2 on 2019-06-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0009_auto_20190324_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='ClassTime',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
