# Generated by Django 2.1.7 on 2019-03-18 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0009_remove_activity_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='level',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AddField(
            model_name='activity',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'Podstawowa'), (2, 'Średnio-zaawansowana'), (3, 'Zaawansowana')], default=1),
        ),
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='max_capacity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='control_panel.Activity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
