# Generated by Django 2.0.2 on 2018-03-21 11:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0009_pass_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 21, 11, 14, 57, 411135, tzinfo=utc), verbose_name='Data rozpoczęcia'),
        ),
    ]
