# Generated by Django 2.0.2 on 2018-03-21 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0010_auto_20180321_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 3, 21), verbose_name='Data rozpoczęcia'),
        ),
    ]
