# Generated by Django 2.1.7 on 2019-03-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0010_auto_20190318_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='classtime',
            name='day',
            field=models.ManyToManyField(to='control_panel.Day'),
        ),
        migrations.AddField(
            model_name='classtime',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.Group'),
        ),
    ]
