# Generated by Django 2.0.2 on 2018-03-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0011_auto_20180321_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='available_entries',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pass',
            name='end_date',
            field=models.DateField(),
        ),
    ]
