# Generated by Django 2.1.7 on 2019-03-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0011_auto_20190318_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtime',
            old_name='day',
            new_name='days',
        ),
    ]
