# Generated by Django 2.0.2 on 2018-03-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0012_auto_20180321_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='entries',
            new_name='available_entries',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='available_entries',
        ),
        migrations.AddField(
            model_name='pass',
            name='entries',
            field=models.SmallIntegerField(default=0),
        ),
    ]
