# Generated by Django 2.0.2 on 2018-03-22 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0014_auto_20180321_1602'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Group',
        ),
        migrations.AlterField(
            model_name='pass',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 3, 22), verbose_name='Data rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='product',
            name='activity',
            field=models.SmallIntegerField(choices=[(1, 'Jumping'), (2, 'Pole Dance'), (3, 'Stretching')], default=2, verbose_name='Rodzaj zajęć'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_entries',
            field=models.SmallIntegerField(verbose_name='Liczba wejść'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='product',
            name='validity',
            field=models.SmallIntegerField(default=30, verbose_name='Termin ważności'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='mail',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.IntegerField(verbose_name='Numer tel.'),
        ),
    ]
