# Generated by Django 2.0.2 on 2018-03-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0015_auto_20180322_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='trainer',
            field=models.ForeignKey(on_delete=None, related_name='groups', to='control_panel.Trainer'),
        ),
    ]
