# Generated by Django 2.0.2 on 2018-03-23 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0016_auto_20180322_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 3, 23), verbose_name='Data rozpoczęcia'),
        ),
    ]
