# Generated by Django 2.0.2 on 2018-03-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0017_auto_20180323_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'Podstawowa'), (2, 'Średnio-zaawansowana'), (3, 'Zaawansowana')], default=1, verbose_name='Poziom'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='control_panel.Member', verbose_name='Członkowie grupy'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='group',
            name='program',
            field=models.IntegerField(choices=[(1, 'Jumping'), (2, 'Pole Dance'), (3, 'Stretching')], verbose_name='Rodzaj zajęć'),
        ),
        migrations.AlterField(
            model_name='group',
            name='trainer',
            field=models.ForeignKey(on_delete=None, related_name='groups', to='control_panel.Trainer', verbose_name='Instruktor'),
        ),
    ]
