# Generated by Django 2.0.2 on 2018-03-28 17:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0018_auto_20180323_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='pass',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 3, 28), verbose_name='Data rozpoczęcia'),
        ),
        migrations.AddField(
            model_name='entry',
            name='current_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.Pass'),
        ),
    ]
