# Generated by Django 2.0.2 on 2018-04-03 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0020_auto_20180331_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='current_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.Pass'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 4, 3), verbose_name='Data rozpoczęcia'),
        ),
    ]
